version: '{build}'
image: Visual Studio 2019

init:
  - ps: |
      If($Env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$Env:APPVEYOR_REPO_TAG_NAME"
      } 
      else 
      {
        $releases = "https://api.github.com/repos/$env:APPVEYOR_REPO_NAME/releases"
        $tag = (Invoke-WebRequest $releases | ConvertFrom-Json)[0].tag_name
        Update-AppveyorBuild -Version "$tag.$Env:APPVEYOR_BUILD_VERSION-wip"
      }
      Write-Host "Hello. Build version is: $Env:APPVEYOR_BUILD_VERSION"

before_build:
- cmd: >-
    nuget restore
# version
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build:
  publish_nuget: true
  include_nuget_references: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  project: SpecklePopup.sln
  verbosity: minimal

afterbuild:
   - 7z a -tzip -r SpeckleAccountManager.zip "%APPVEYOR_BUILD_FOLDER%\Release\*"
deploy:
  - provider: GitHub
    release: SpeckleAccountManager-v$(APPVEYOR_REPO_TAG_NAME)
    tag: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: D5tPFvdQMg9sIe0sSvQjEWw4KAdOk1jyxNwiH5qP5DpDmUH6n6NgTdA+56vXS1Pe
    artifact: SpeckleAccountManager.zip
    on:              
      appveyor_repo_tag: true
  - provider: NuGet
    server:                  # remove to push to NuGet.org
    api_key:
      secure: n4EiHDLVSLjOzqT7OOOg3US3PWs6fNsOaGpyT/EFBKrTKl/1wMmmKt73MNuTngD+
    skip_symbols: false
    symbol_server:           # remove to push symbols to SymbolSource.org
    on:
      APPVEYOR_REPO_TAG: true

notifications:
- provider: Slack
  incoming_webhook:
    secure: 9Kt/ImvGdsQ/dzmRdSaMIG+BO0R29MOJC7eZZnK5m5TyWwE+4nofEcYlb/r4lh9Z1Dx/bR+7oQtgAYO3W5s+qJshkT6Is9irYw3TfMZX7/M=
  channel: '#devtalk'
  template: Build <{{buildUrl}}|#{{buildVersion}}> (<{{commitUrl}}|{{commitId}}>) of {{repositoryName}}@{{branch}}) by {{commitAuthor}} {{status}} in {{duration}}
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

configuration:
  - Release
